# Generated by Django 5.1.6 on 2025-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('bio_text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
            ],
        ),
    ]
